apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
    - name: web
      protocol: TCP
      port: 9001
      targetPort: 80
    
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
  type: ClusterIP
